//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBService
{
    using System;
    using System.Collections.Generic;
    
    public partial class operationrecord
    {
        public long ID { get; set; }
        public string UID { get; set; }
        public System.DateTime ModifiedTime { get; set; }
        public string Data { get; set; }
        public Nullable<System.DateTime> RTC { get; set; }
        public int ResultID { get; set; }
        public Nullable<System.DateTime> MCUCheckTime { get; set; }
        public int LoopNumber { get; set; }
        public short OperationID { get; set; }
        public string Comments { get; set; }
        public string TotalVoltage { get; set; }
        public string Current { get; set; }
        public string CellVoltage { get; set; }
        public string AmbientTemp { get; set; }
        public string CellTemp { get; set; }
        public string Humidity { get; set; }
        public string UserID { get; set; }
        public string Pre_AdjustCurrentVal { get; set; }
        public string AdjustCurrentVal { get; set; }
    
        public virtual operation operation { get; set; }
        public virtual result result { get; set; }
        public virtual users users { get; set; }
    }
}
